apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
  - image: wordpress
    name: wordpress
    env:
    - name: password
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
    - name: user
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: user